"use client";

import {
  formatAiDraftRelativeTime,
  type AiDraftSession,
} from "@/data/aiDraftReview";
import { cn } from "@/lib/cn";

type AiDraftSummaryCardProps = {
  session: AiDraftSession;
  className?: string;
};

/**
 * Compact generation summary shown above the outbound email editor.
 */
export function AiDraftSummaryCard({ session, className }: AiDraftSummaryCardProps) {
  const items = [
    { label: "Generated by", value: session.generatedBy },
    { label: "Generated", value: formatAiDraftRelativeTime(session.generatedAtMs) },
    { label: "Language", value: session.language },
    { label: "Tone", value: session.tone },
    { label: "Template", value: session.selectedTemplate },
  ] as const;

  return (
    <aside
      className={cn("send-center-ai-draft-summary-card", className)}
      aria-label="AI draft summary"
    >
      <h4 className="send-center-ai-draft-summary-title">AI Draft</h4>
      <dl className="send-center-ai-draft-summary-grid">
        {items.map((item) => (
          <div key={item.label} className="send-center-ai-draft-summary-item">
            <dt>{item.label}:</dt>
            <dd>{item.value}</dd>
          </div>
        ))}
      </dl>
    </aside>
  );
}
